server:
  port: 8050

spring:
  application:
    name: user-zuul

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka

looging:
  level:
    root: INFO

zuul:
  # ignoredServices: '*' # 多个路由
  routes:
    app-user:
      path: /user/**
      serviceId: user-consumer