server:
  port: 8010

spring:
  application:
    name: user-consumer

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka

looging:
  level:
    root: INFO